stages:
  prepare_data:
    cmd: python scripts\prepare_data.py
    deps:
    - data\raw\datos_creditos.csv
    - data\raw\datos_tarjetas.csv
    - scripts\prepare_data.py
    outs:
    - data\processed\datos_integrados.csv
    - reports\prepare_data_summary.json
